tp_2_partie_2_prog_moa_gc/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// le nom du controlleur et la méthode  entre ' ' :
Route::get('/', 'FilmsController@index');
// Route::get('/about', 'PagesController@about');
// Route::get('/services', 'PagesController@services');

// Route::get('/users/edit', 'UsersController@edit');
Route::name('language')->get('language/{lang}', 'HomeController@language');

Route::resource('/users','UsersController');

Route::resource('/films', 'FilmsController');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// page de recherche
Route::get('/search', 'FilmsController@search')->name('search');

// recherche ajax
Route::post('/searchajax', 'FilmsController@searchajax');

Route::post('/searchuserajax', 'UsersController@searchuserajax');

Route::post('/films/{film}/critiques' , 'CritiquesController@store');
Route::get('/films/{critique}/editCritique' , 'CritiquesController@edit');
Route::post('films/{critique}/updatecritiques' , 'CritiquesController@update');

Route::delete('films/{critique}/deletecritique' , 'CritiquesController@destroy');
// Route::resource('/films', 'CritiquesController');

// Route::post('/searchuserajax',)

tp_2_partie_2_prog_moa_gc/resources/views/inc/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach

@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

tp_2_partie_2_prog_moa_gc/resources/views/inc/navbar.blade.php
<div>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;
            </ul>


            <ul class="nav navbar-nav">
                <li><a href="{{ route('films.index') }}">Accueil</a></li>
                <li><a href="{{ route('search') }}">Rechercher</a></li>
                {{--  <li><a href="/services">Services</a></li>  --}}
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @guest
                    <li><a href="{{ route('login') }}">Se connecter</a></li>
                    <li><a href="{{ route('register') }}">S'inscrire</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="/home">Bureau</a></li>
                            <li>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                    Se déconnecter
                                </a>
                                <a href="/users/{{ Auth::id() }}/edit">Modifier le compte</a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
</div>